################################################################################
## File name        : K8s_Installation_Playbook.yaml                          ##
## Author           : Arash Foroughi                                          ##
## Version          : v1.0                                                    ##
## Created          : 2022-07-11                                              ##
## Modified Time    :                                                         ##
## Change records   :                                                         ##
################################################################################

#############################################################################################
## This play will disable swap feature in all nodes, because of Kubernetes recommendation. ##
#############################################################################################
- name: STEP-1-Disable Swap
  hosts: all 

  tasks: 
    - name: Disable Swap on All Nodes
      command: "swapoff -a"

    - name: Disable Swap Permanently on All Nodes
      lineinfile:
        dest: /etc/fstab
        state: absent
        regexp: "swap.img"
        backup: yes

######################################################################################        
## This play will install docker as container runtime and confiure it on all nodes. ##
######################################################################################

- name: STEP-2-Install Docker
  hosts: all

  tasks:
    - name: Install Docker Dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
        update_cache: yes
        state: latest

    - name: Adding Docker-Repo GPG-Key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /root/docker-keyring.gpg
        mode: 0755
        force: yes

    - name: Check Existence of Docker GPG-Key
      stat:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
      register: result1

    - name: Encrypt the Docker GPG-Key
      shell: "cat /root/docker-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
      when: not result1.stat.exists

    - name: Add Docker Repository
      shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      register: result2

    - name: Add Docker Repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          {{ result2.stdout }}
        force: yes

    - name: Install Docker Community Edition on All Nodes
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        update_cache: yes
        state: latest

    - name: Force Docker Daemon to Use Native-Cgroup-Driver
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
        force: yes

    - name: Reloading Docker Daemon
      command: "systemctl daemon-reload"

    - name: Enabling & Restarting Docker Daemon
      service:
        name: docker
        enabled: yes
        state: started

###################################################################
## This play will install kubeadm, kubectl, kubelet on all nodes"##
###################################################################
- name: STEP-3-Install Kubernetes Packages
  hosts: all

  tasks:
    - name: Adding Kubernetes-Repo GPG-Key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /root/kubernetes-keyring.gpg
        mode: 0755
        force: yes

    - name: Check Existence of Kubernetes GPG-Key
      stat:
        path: /usr/share/keyrings/kubernetes-archive-keyring.gpg
      register: result3

    - name: Pack the Kubernetes GPG-Key
      shell: "cat /root/kubernetes-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg"
      when: not result3.stat.exists

    - name: Add Kubernetes Repository
      shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
      register: result4

    - name: Add Kubernetes Repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          {{ result4.stdout }}
        force: yes

    - name: Install Kubernetes Version 1.23.6 on All Nodes
      apt:
        name: ['kubeadm=1.23.8-00', 'kubectl=1.23.8-00', 'kubelet=1.23.8-00']
        update_cache: yes
        state: present

    - name: Prevent Kubernetes from Upgrading in the Future
      command: "apt-mark hold kubeadm kubectl kubelet"


    - name: Update Sysctl Settings for K8s Networking
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
        force: yes
