## Vote-App Web Server Deployment ##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: inpress/assignment:voteapp-latest
        ports:
        - containerPort: 80
          name: vote
---
## Vote-App Web Server SVC ##
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    apps: vote
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 30008
      name: vote-service
  selector:
    app: vote